name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install elm
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - name: Compile
      run: elm make --optimize --output=dist/index.html Main.elm
    - name: Minify
      # https://guide.elm-lang.org/optimization/asset_size.html
      run: |
        npx html-minifier-terser \
          --minify-js '{"compress": { "pure_funcs": ["F2","F3","F4","F5","F6","F7","F8","F9","A2","A3","A4","A5","A6","A7","A8","A9"], "pure_getters": true, "keep_fargs": false, "unsafe_comps": true, "unsafe": true } }' \
          --output dist/index.html \
          dist/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

